### ISSUE TITLE
mod_reservation breaks latest Moodle 3.1dev 

### ISSUE THREAD

**Issue by ewallah** [bobopinna/moodle-mod_reservation#3]
Moodle 3.1dev (Build: 20160422)

PHP Fatal error:  Call to undefined method flexible_table::get_download_menu() in mod/reservation/settings.php on line 29.

**Comment by bobopinna** [comment]
We can't use that method anymore. I've removed default download format in plugin settings.
Now it seem to work fine.

**Comment by jderriks** [comment]
Googling "Call to undefined method flexible_table::get_download_menu() " resulted in this page so for everyone that gets stuck with a broken Moodle because they didn't update their plugins first, here is the quick fix:
1. repace the mod/reservation folder with the new one (git clone or download+copy)
2. goto moodle notifications and upgrade db.

Next time don't upgrade without checking plugins first.
